package com.example.javacodeagent.tool;

import dev.langchain4j.agent.tool.Tool;
import org.springframework.stereotype.Component;

/**
 * 工具：自动生成 JUnit5 单元测试用例
 * 作用：验证代码逻辑是否正确，自动生成测试代码
 */
@Component
public class JavaCodeTestGeneratorTool {

    @Tool
    public String generateUnitTest(String javaCode) {
        StringBuilder testResult = new StringBuilder();
        testResult.append("✅ 【AI 自动生成 · JUnit5 单元测试】\n");
        testResult.append("=======================================\n");

        // 通用测试代码模板（企业级标准写法）
        testResult.append("import org.junit.jupiter.api.Test;\n");
        testResult.append("import static org.junit.jupiter.api.Assertions.*;\n\n");
        testResult.append("public class AutoGeneratedTest {\n\n");

        // 根据代码特征智能生成对应测试
        if (javaCode.contains("add(") || javaCode.contains("int")) {
            // 数字计算方法测试
            testResult.append("    @Test\n    void testCalculate() {\n");
            testResult.append("        // 正常场景\n");
            testResult.append("        assertEquals(5, add(2, 3));\n");
            testResult.append("        // 边界场景：负数\n");
            testResult.append("        assertEquals(0, add(-2, 2));\n");
            testResult.append("        // 边界场景：零\n");
            testResult.append("        assertEquals(9, add(9, 0));\n");
            testResult.append("    }\n");
        } else if (javaCode.contains("String")) {
            // 字符串处理测试
            testResult.append("    @Test\n    void testStringProcess() {\n");
            testResult.append("        assertNotNull(yourMethod(\"test\"));\n");
            testResult.append("        assertEquals(\"TEST\", yourMethod(\"test\"));\n");
            testResult.append("    }\n");
        } else {
            // 通用业务逻辑测试
            testResult.append("    @Test\n    void testBusinessLogic() {\n");
            testResult.append("        // 测试不抛异常\n");
            testResult.append("        assertDoesNotThrow(() -> yourMethod());\n");
            testResult.append("        // 测试结果非空\n");
            testResult.append("        assertNotNull(yourMethod());\n");
            testResult.append("    }\n");
        }

        testResult.append("}\n");
        testResult.append("\n使用方式：放到 test 目录，直接运行 JUnit5！");

        return testResult.toString();
    }
}
